# dependatbot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:10"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    reviewers:
      - "vthanhduong"
